name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: mkdir Executables; make install
    - name: make check
      run: make gentests; ./unittests
    - name: run for checking
      run: ./Executables/hash_based_dist ./Input_DNA/covid.fasta 4

